### ISSUE TITLE
Missing required parameters recaptcha!

### ISSUE THREAD

**Issue by GiantHoax** [mageplaza/magento-2-google-recaptcha#10]
Hello,
I installed this plugin, but when i use it on the login i get the following error:
Missing required parameters recaptcha! I get this after i try to login and it gives me a blank page with this as url:
customer/account/loginPost/
How can i fix this?

**Comment by Arthas78** [comment]
Have you installed the lib for ReCaptcha? If not, please install it as instructed
https://docs.mageplaza.com/google-recaptcha/index.html(https://i.imgur.com/Kh8q150.png)

**Comment by Arthas78** [comment]
You can download lib here
https://github.com/mageplaza/magento-2-google-recaptcha/tree/library

**Comment by rajesh0608** [comment]
Hi Friend,

I have some things module related issue. 

After Installing the module and adding google site key and secret key on the frontpage I got  such error "This site key is not enabled for the invisible captcha. " with google captcha icon.

please help me out this.


![capcha-eeror](https://user-images.githubusercontent.com/11803927/52916929-55e15b80-330b-11e9-9cbf-1861579f4df5.png)

**Comment by GiantHoax** [comment]
Hello,
Go to this site: https://www.google.com/recaptcha/admin/create
and enable invisible recaptcha badge (second option)
![afbeelding](https://user-images.githubusercontent.com/10993605/52917073-549e3780-32e7-11e9-863e-bc6b8238103e.png)

**Comment by rajesh0608** [comment]
Thanks.
It's working now.

Again Thanks for your quick response.

**Comment by GiantHoax** [comment]
Not a problem

**Comment by rajesh0608** [comment]
Hello @GiantHoax 
I have another query,
A form has id eg. " inquiry-id" which is called at 2 different places.
so this id used at mageplaza recaptcha, But recaptcha didn't show on frontend page.
Will you please know me how to add captcha on a customs form?

**Comment by Marko675** [comment]
Error: Invalid API parameters. Can u help me?
