### ISSUE TITLE
Is it Possible to show the visible captcha checkbox on frontend?

### ISSUE THREAD

**Issue by blaine12100** [mageplaza/magento-2-google-recaptcha#12]
Hi

Thank you for this extension.I would like to know that is it possible to show the visible captcha like on the admin side on the frontend forms?

Right now the invisible captcha works but i would still like my users to check on the box and then proceed to login.

**Comment by bien119** [comment]
Hi,
Currently, our extension only shows invisible captcha for frontend page and visible captcha (checkbox) for the admin page. I'm so sorry for that but we're having plans to brings visible captcha to both backend and frontend.
Hope you wait for the next version.

**Comment by bien119** [comment]
This issue will be closed. Hope you wait for the next version.
