### ISSUE TITLE
Create user form not showing recaptcha

### ISSUE THREAD

**Issue by CraigDaveyinLIFE** [mageplaza/magento-2-google-recaptcha#14]
Magento Installation Info:
V: 2.2.3

I am having the issue with the plugin not showing the recaptcha on the create user form however it does show on the review form.

The recaptcha is also showing on the admin side fine.

Can you please give me some ideas on how I can get this working.

Thanks

**Comment by bien119** [comment]
Did you edit something on the create user form or you still use the default create user form of Magneto?
Please clean the cache beforehand. Maybe it's the main cause.

**Comment by bien119** [comment]
@CraigDaveyinLIFE I'll close this issue (No response in 7 days). Hope you find the best solution for that.
