### ISSUE TITLE
Recaptcha ignores store view locale

### ISSUE THREAD

**Issue by mkor** [mageplaza/magento-2-google-recaptcha#16]
Heya guys,
First a thank-you for the nice, free module.
Still, I wonder why you included a setting that allows one to select the Google reCaptcha language, but did NOT add the option to make it use the store view's locale?

Having similar settings all over the place is generally a bad idea because most people are not structured enough to properly keep track of this.
Plus, it becomes rather frustrating for setups with 10s to 100s of mixed-language store views, because

1. We now have to duplicate the language-setting.
2. We now have to keep these settings in-synch.

Correct usage would be to either remove the setting entirely (perhaps making it a PRO feature?) OR make it point to "general/locale/code" by default (dropping the country-part from the locale; and dont do it like the current auto-detect that then happily caches the current result)

**Comment by Arthas78** [comment]
Each store view has a different section of Google Recaptcha configuration, you can configure it here
http://prntscr.com/mjx683

**Comment by mkor** [comment]
![screen shot 2019-02-14 at 14 04 56](https://user-images.githubusercontent.com/123557/52788711-0fb59f00-3062-11e9-91fb-1d0fd6e739ce.png)
But a store view's language is configured here.

**Comment by Arthas78** [comment]
Please go to the store view you need then go to the google Recaptcha module section and configure it here http://prntscr.com/mlb9ps
This module is a support to add re-captcha so if you want to change the language of captcha in each store view, you need to change the captcha configuration.

**Comment by mkor** [comment]
@Arthas78 That is illogical. With such a setting, you're basically saying "just set it to English and don't bother about those other languages"

After all, that setting is like saying that the first time you go to a store, you have to fill in a form affirming that you want to be able to pay with USD when you go to a different store in the USA. For every store you visit for the first time.

**Comment by Arthas78** [comment]
That install is only for the google-recaptcha module, it does not affect anything on your store view. With each of your store views, you can set it to switch to the language you want

**Comment by Arthas78** [comment]
Since your issue has been resolved, I will close the issue here
