### ISSUE TITLE
This site key is not enabled for the invisible captcha.

### ISSUE THREAD

**Issue by rajesh0608** [mageplaza/magento-2-google-recaptcha#18]
Hi, 
I installed a module on Magento 2.2.7 version, after adding google site key and secret key on admin panel.
I faced error on front page "This site key is not enabled for the invisible captcha.".
Please help me out this issue.

![image](https://user-images.githubusercontent.com/11803927/52917086-3fd49a80-330d-11e9-9cc4-0a0950d91f5d.png)

**Comment by Arthas78** [comment]
Sorry for the late reply. Our working day has started. I see your issue has been resolved here 
http://prntscr.com/mmhow8
so I will close this issue

**Comment by rajesh0608** [comment]
Hi friend,
Thanks for your reply. An issue has been resolved.

**Comment by rajesh0608** [comment]
Hi Friend,

I have another query,
A form has id eg. " inquiry-id" which is called at 2 different places.
so this id used at mageplaza recaptcha, But recaptcha didn't show on frontend page.
Will you please know me how to add captcha on a customs form?
