### ISSUE TITLE
Fatal error: Uncaught Error: Class 'ReCaptcha\ReCaptcha' not found in Data.php:259 

### ISSUE THREAD

**Issue by thomas-harding** [mageplaza/magento-2-google-recaptcha#2]
Hey,

Installed Recaptcha on Magento Open Source 2.2.4 and when I go to submit a contact form for example, I get the following error:

`Fatal error: Uncaught Error: Class 'ReCaptcha\ReCaptcha' not found in /home/user/public_html/app/code/Mageplaza/GoogleRecaptcha/Helper/Data.php:259 Stack trace: #0 /home/user/public_html/app/code/Mageplaza/GoogleRecaptcha/Observer/Captcha.php(107): Mageplaza\GoogleRecaptcha\Helper\Data->verifyResponse() #1 /home/user/public_html/vendor/magento/framework/Event/Invoker/InvokerDefault.php(72): Mageplaza\GoogleRecaptcha\Observer\Captcha->execute(Object(Magento\Framework\Event\Observer)) #2 /home/user/public_html/vendor/magento/framework/Event/Invoker/InvokerDefault.php(60): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod(Object(Mageplaza\GoogleRecaptcha\Observer\Captcha), Object(Magento\Framework\Event\Observer)) #3 /home/user/public_html/vendor/magento/framework/Event/Manager.php(66): Magento\Framework\Event\Invoker\InvokerDefault->dispatch(Array, Object(Magento\Framework\Event\Observer)) #4 /home/user/public_html/generated/code/Magen in /home/user/public_html/app/code/Mageplaza/GoogleRecaptcha/Helper/Data.php on line 259`

I downloaded it from your store (as opposed to getting it from GitHub).

Thanks
Tom

**Comment by MyoDaisy** [comment]
In order to solve this issue, you can rename the library Recaptcha in lib/internal/Mageplaza/GoogleRecaptch/ to ReCaptcha

**Comment by thomas-harding** [comment]
This fixed it, thank you very much :)
