### ISSUE TITLE
Adding recaptcha to the checkout page

### ISSUE THREAD

**Issue by LandonL82** [mageplaza/magento-2-google-recaptcha#20]
I can't seem to get recaptcha added to the checkout page at domain.com/checkout

I am using checkout/#payment as the Form Post Path, and #co-payment-form as the CSS selector, but it seems to simply loop back to the page when I try to checkout. 

Any advice would be appreciated.

**Comment by bien119** [comment]
@LandonL82 Please try using "checkout/onepage/saveorder/" for Form Post Path. Screenshot below:

- http://prntscr.com/n0uap8

- http://prntscr.com/n0ub8b

**Comment by LandonL82** [comment]
Hi Bien119,

Thank you for the advice, however it does not work.  When I press Place Order the wheel spins for 1 second, then nothing.  The order does not complete on the backend either.

**Comment by bien119** [comment]
Hi @LandonL82 For me, captcha is working with checkout/onepage/saveorder/
Do you get any error message after placing the order?

**Comment by bien119** [comment]
This issue will be closed (no response in 7 days). If your issue is not resolved, please let me know more further detail.

**Comment by ezest-rajesh** [comment]
Hi

Captcha is not working on the checkout page with a credit card form.
could you please assist with how to enable it on the checkout page.

**Comment by yavuz** [comment]
I did this temporarily.

I added in checkout_index_index.xml

`<head><script src="//www.google.com/recaptcha/api.js?render=_reCAPTCHA_site_key" src_type="url" /></head>`

and I wrote css selectors: #co-payment-form

It's works for me.

**Comment by ezest-rajesh** [comment]
Thanks for reply,

how you will handle server side validation for the recaptcha?

Best Regards,
Rathod Rathod
________________________________

**Comment by yavuz** [comment]
Sorry. Mine was for frontend validation(Invisible Captcha).

**Comment by robeka** [comment]
@yavuz Kindly share your complete code.

**Comment by ahsanaimer** [comment]
@yavuz  Kindly share your complete code.

**Comment by lash23** [comment]
> I did this temporarily.
> 
> I added in checkout_index_index.xml
> 
> `<head><script src="//www.google.com/recaptcha/api.js?render=_reCAPTCHA_site_key" src_type="url" /></head>`
> 
> and I wrote css selectors: #co-payment-form
> 
> It works for me.

It works for me too,
for reference, remember to change the **__reCAPTCHA_site_key_** for your own Google reCaptcha site key

**Comment by aliomattux** [comment]
As another person asked, please paste the complete solution. Just adding the script reference in the checkout layout file isn't sufficient for me to get the solution working.

I tried also what the first person suggests about using the custom form feature. For me the recaptcha shows but it does not prevent bots from placing orders on the site I am looking at.

**Comment by jas8522** [comment]
I followed @bien119 steps above, using:
- `checkout/onepage/saveorder/`
- `#co-payment-form` (css selector)
It didn't work for visible recaptcha, but it does work for invisible -- so you *must* save invisible recaptcha keys in the settings and then configure it to use invisible recaptcha on front-end for it to work.

**Comment by yavuz** [comment]
> I did this temporarily.
> 
> I added in checkout_index_index.xml
> 
> `<head><script src="//www.google.com/recaptcha/api.js?render=_reCAPTCHA_site_key" src_type="url" /></head>`
> 
> and I wrote css selectors: #co-payment-form
> 
> It works for me.

This solution doesn't work. It shows working but server validation not working. Be careful!

**Comment by PurushothamanKrishnamoorthy** [comment]
I'm facing this issue with Magento 2.4.1 Has anyone found solution for this issue
