### ISSUE TITLE
Missing language code

### ISSUE THREAD

**Issue by mcandian** [mageplaza/magento-2-google-recaptcha#21]
I miss the default german (de) as language code. Can you please add it?

Perhaps there are more missing language codes. Here the full list of language code from Google:
https://developers.google.com/recaptcha/docs/language

**Comment by bien119** [comment]
@mcandian Please open Mageplaza\GoogleRecaptcha\Model\System\Config\Source\Language.php
You can use German by adding **['label' => __('German'), 'value' => 'de']** into the option array.
Screenshot: http://prntscr.com/n195yp

**Comment by bien119** [comment]
@mcandian This issue will be closed (no response in 7 days). Hope you have the best result with my solution.

**Comment by OvalMedia** [comment]
Will this be added to the repo?
