### ISSUE TITLE
"The request is invalid or malformed" when create account

### ISSUE THREAD

**Issue by kriswen** [mageplaza/magento-2-google-recaptcha#22]
getting "The request is invalid or malformed" message when submit create account, however, the sign up does go through.

**Comment by bien119** [comment]
@kriswen Have you ever modified anything on the create form? Could you show me your configuration of google recaptcha extension?

**Comment by kriswen** [comment]
Hi,
   No, nothing was modified. I recently enable gzip compression on my
website, i'm not sure if that could be the cause to the problem?

General: Enable
Invisible:  API Key/ Secret Key
Visible: empty
Backend: No
Frontend: Enable ( all selected)
Position: button right
theme: light


Thank you in advance,

Kris

**Comment by bien119** [comment]
Gzip could be the main cause. Is your issue solved?

**Comment by kriswen** [comment]
Hi Bien,
    No, the issue still presist. the following is what i added it to the .htaccess file in the root, so these could cause the issue? Thanks for getting back to me.

<IfModule mod_gzip.c>
mod_gzip_static_suffix .gz
AddEncoding gzip .gz
AddEncoding gzip .gzip
mod_gzip_on YES
mod_gzip_handle_methods GET
mod_gzip_temp_dir /tmp
mod_gzip_can_negotiate Yes
mod_gzip_dechunk Yes
mod_gzip_send_vary On
mod_gzip_update_static No
mod_gzip_keep_workfiles No
mod_gzip_minimum_file_size 250
mod_gzip_maximum_file_size 1048576
mod_gzip_maximum_inmem_size 60000
mod_gzip_min_http 1000
mod_gzip_item_exclude reqheader "User-agent: Mozilla/4.0[678]"
mod_gzip_item_exclude file .js$
mod_gzip_item_exclude file .css$
mod_gzip_item_exclude mime ^application/pdf$
mod_gzip_item_exclude mime ^image/
mod_gzip_item_exclude mime ^application/x-javascript$
mod_gzip_item_include mime ^text/.*
mod_gzip_item_include file .html$
mod_gzip_item_include file .pl$
mod_gzip_item_include file .cgi$
mod_gzip_item_include handler ^cgi-script$
mod_gzip_item_include mime ^httpd/unix-directory$
mod_gzip_item_include mime ^application/postscript$
</IfModule>

**Comment by MpEdward** [comment]
@kriswen Has the issue with this module has been resolved?
If it has been resolved, I will close this ticket. Thank you!

**Comment by kriswen** [comment]
Hi, 
    Adding the create account page to the exclude list seems to fix the issue. Will close this for now. Thank you.
