### ISSUE TITLE
$.widget is not a function

### ISSUE THREAD

**Issue by EirikSl** [mageplaza/magento-2-google-recaptcha#23]
captcha.js  needs to use require Js extra dependency 'jquery/ui'
In other cases  line 26 "$.widget('mageplaza.captcha'," can produse in some situations error: "$.widget is not a function". Please fix that.

**Comment by bien119** [comment]
@EirikSl, could you give me some screenshot of your error?
Please get me more detail about it so that I can reproduce it on my local.

**Comment by EirikSl** [comment]
@bien119 I customized Js bundles for magento 2. But I think my way to catch this error isn’t important. As you you know in define array we place requireJs dependencies. Now you have only jquery there,but “$.widget” method is part of jqueryUi lib. Sorry I am typing from phone now and can’t send you screenshots, but should I?

**Comment by MpEdward** [comment]
@EirikSl Please send us some screenshots about it. we're wating for you.

**Comment by MpEdward** [comment]
It was over 7 days and I didn't receive any reply so I will close this ticket.
Thank you!
