### ISSUE TITLE
Add Support for PayPal to address recent vulnerability issues.

### ISSUE THREAD

**Issue by LandonL82** [mageplaza/magento-2-google-recaptcha#24]
Due to the new vulnerability mentioned and addressed here:

https://support.magento.com/hc/en-us/articles/360025515991-PayPal-Payflow-Pro-active-carding-activity

It has required using the methods mentioned there to deal with the problem.

This conflicts with the mageplaza/magento-2-google-recaptcha module.

Would it be possible to add support for Paypal/Payflow recaptcha on the checkout page?

Here is the solution implemented in the above method.

https://github.com/magento/PayPalReCaptcha

Can this functionality be added to the mageplaza module?  I much prefer the mageplaza module versus the MSP one, and it seems I cannot use them both together.

**Comment by bien119** [comment]
@LandonL82 our team will check and let you know the result as soon as possible.

**Comment by Desmond-Mageplaza** [comment]
We are currently aware of this problem and we are updating the module to integrate with this new feature from PayPal.
The updated version of the module will be released soon.
Please watch the Google ReCaptcha repository for the latest version.
Thank you!
