### ISSUE TITLE
"missing sitekey" from frontend

### ISSUE THREAD

**Issue by Frostmoore** [mageplaza/magento-2-google-recaptcha#26]
Hello there, I installed this extension, but I can't see the checkbox on the frontend. It always gives me "missing parameters: sitekey", though I installed the recaptcha lib, I generated the checkbox keys and I entered them in the extension configuration. I selected all of the default forms from the configuration page.

**Comment by bien119** [comment]
@Frostmoore  Checkbox captcha is used in the backend, not the frontend.
 In the frontend, we use invisible captcha. So if you want to use this feature, I'm so sorry.
Please wait for the next version.

**Comment by bien119** [comment]
Hope you wait for the next version. Currently, I'll close this ticket.
