### ISSUE TITLE
HTTP 500 error

### ISSUE THREAD

**Issue by joysaach** [mageplaza/magento-2-google-recaptcha#27]
Website goes download when i enable the plugin , it shows http 500 error .Im using magento 2.2.4

**Comment by MpEdward** [comment]
Hi,
I'm Edward from Mageplaza.

Have you installed our module Core?

**Comment by joysaach** [comment]
yes i have , the site shows error after core installation.

**Comment by MpEdward** [comment]
Have you installed the lib of this module?
If you have fully installed the error still occurs. Please create a new ticket on Freshdesk so we can support you more easily.

**Comment by MpEdward** [comment]
It was over 7 days and I didn't receive any reply so I will close this ticket.
Thank you!
