### ISSUE TITLE
Uncaught Error: Class 'ReCaptcha\ReCaptcha' not found

### ISSUE THREAD

**Issue by saigadekar** [mageplaza/magento-2-google-recaptcha#28]
While submitting the form to create new customer account. i am getting below error.

I tried using the fix provided for https://github.com/mageplaza/magento-2-google-recaptcha/issues/2
but its not working

PHP Fatal error:  Uncaught Error: Class 'ReCaptcha\ReCaptcha' not found in app/code/Mageplaza/GoogleRecaptcha/Helper/Data.php:291

Please help

**Comment by MpEdward** [comment]
Hi,
I'm Edward from Mageplaza.

Have you installed the library of this module?
If not, please download and install follow the path: lib/internal/mageplaza/Recaptcha
Link to download: https://github.com/mageplaza/magento-2-google-recaptcha/tree/library

**Comment by saigadekar** [comment]
Thanks it working

**Comment by waymanxie** [comment]
> Hi,
> I'm Edward from Mageplaza.
> 
> Have you installed the library of this module?
> If not, please download and install follow the path: lib/internal/mageplaza/Recaptcha
> Link to download: https://github.com/mageplaza/magento-2-google-recaptcha/tree/library

![image](https://user-images.githubusercontent.com/41362735/68597301-b470ea00-04d7-11ea-9d60-1d8d3ba2a059.png)

I uploaded the module. But still doesn't work. Can you help?

**Comment by MpEdward** [comment]
This is the error because the module library has not been installed.
Please download and install follow the path: lib/internal/mageplaza/Recaptcha
Link to download: https://github.com/mageplaza/magento-2-google-recaptcha/tree/library

**Comment by waymanxie** [comment]
Hi Edward,

Thanks for your reply.
Just copy the folder to the destination? Does it need to be upgraded and
compiled?

Edward <notifications@github.com> 于2019年11月25日周一 上午11:58写道：
