### ISSUE TITLE
The reponse parameter is missing.

### ISSUE THREAD

**Issue by Dan-Coleman** [mageplaza/magento-2-google-recaptcha#29]
After installing on our site, I am getting an error:
The response parameter is missing.

The backend tickbox works but the invisible recaptcha on the contact form is not working. Can you please advise.

**Comment by MpEdward** [comment]
Did you install google recaptcha library? You can find it with the link below.

https://github.com/mageplaza/magento-2-google-recaptcha/tree/library
Library path: https://i.imgur.com/Kh8q150.png

**Comment by MpEdward** [comment]
It was 7 days and I didn't receive any reply so I will close this ticket.
Thank you!
