### ISSUE TITLE
Recaptcha not loading Google api.js

### ISSUE THREAD

**Issue by gvillafanetapia** [mageplaza/magento-2-google-recaptcha#3]
I'm having trouble activating the recaptcha.

When I load any of the forms in which it is activated I see this error in console, and the captcha doesn't load:
![image](https://user-images.githubusercontent.com/10351402/45510775-9bed2e80-b771-11e8-9ffd-80f1f3ecfc7d.png)

Then if I post the form I get a captcha missing error.

Running Magento v2.0.17, JS bundling and minifying enabled, production mode.

It seems like the captcha.js is not being bundled with the rest of the scripts (its being loaded independently), and in pub/static/_requirejs/frontend/.../requirejs-config.js I can't see the mapping of 'mpGoogleReCaptcha' to '//www.google.com/recaptcha/api.js?onload=recaptchaOnload&render=explicit'

After installing the mageplaza core module and the recaptcha module I ran the following commands:

```
php bin/magento setup:upgrade
rm -rf var/di
rm -rf var/generation
php bin/magento setup:di:compile
php bin/magento cache:clean
chmod g+w -R  pub/media/
chmod g+w -R  pub/static/
chmod g+w -R  var
chown magento:www-data -R pub
chown magento:www-data -R var
rm -rf pub/static/frontend
rm -rf var/page_cache/
rm -rf var/cache/
php bin/magento setup:static-content:deploy en_US es_AR -t VTIngenieria/ChimmyChurry
php bin/magento cache:flush
php bin/magento cache:clean
chmod g+w -R  pub/media/
chmod g+w -R  pub/static/
chmod g+w -R  var
chown magento:www-data -R pub
chown magento:www-data -R var
```

Any ideas?

**Comment by bien119** [comment]
Hi there
The error specifies the captcha.js
(\pub\static\frontend\Magento\luma\en_US\Mageplaza_GoogleRecaptcha\js\captcha.js)
can **not** load the 'mpGoogleReCaptcha' from requirejs-config.js
(\app\code\Mageplaza\GoogleRecaptcha\view\frontend\requirejs-config.js)
Some way, maybe the permission is the main cause makes this errors.
Here is my solution, you can see what I did with the screenshot below.

- http://prntscr.com/ku79fk
You need to edit it in both files to load the js directly in the paths:
- \pub\static\frontend\Magento\luma\en_US\Mageplaza_GoogleRecaptcha\js\captcha.js

- \app\code\Mageplaza\GoogleRecaptcha\view\frontend\web\js\captcha.js

**Comment by imsamthomas** [comment]
The URL is: 
`//www.google.com/recaptcha/api.js?onload=recaptchaOnload&render=explicit`

**Comment by gvillafanetapia** [comment]
Ok, that solved the first half of the problem. Although I still don't see why Magento wouldn't compile both the captcha.js file and the requirejs-config into the bundle on static-deploy.

Anyway, its still not working. Now I get this:

![image](https://user-images.githubusercontent.com/10351402/45554172-1d919a80-b80c-11e8-83cf-1eb477f49c73.png)

Seems like the captcha response is not being sent in the form post. I checked and grecaptcha.execute is being called, and it triggers the callback which has the token. I manually set the token to the g-recaptcha-response input but still no luck:

```
'callback': function(token) {
    if (token) {
        checkSubmitType = 1;
        document.getElementById("g-recaptcha-response").text = token; //I added this
        buttonElement.click();
    } else {
         grecaptcha.reset(resetForm);
         resetForm = 0;
    }
},
```

**Comment by bien119** [comment]
I suppose that the error comes from your wrong google API secret key.
You are using Wrong key or you can confuse between Visible Secret Key and Invisible Secret Key
Please follow the document (https://docs.mageplaza.com/google-recaptcha/index.html).
Then fill the secret key again.

**Comment by gvillafanetapia** [comment]
That was it.. was missing a dash in the end of the secret.
Thank you!

**Comment by bajula** [comment]
I can confirm that a wrong api key can cause this error. 
In my case I  had the wrong Google API Secret Key.
