### ISSUE TITLE
Does not work on password forgotten page

### ISSUE THREAD

**Issue by OvalMedia** [mageplaza/magento-2-google-recaptcha#32]
Magento 2.2.9
Module Version 1.0.3

Module is configured to display reCaptcha on the password forgotten request page. 
reCaptcha does not show up after entering email address or after clicking the submit button. Instead I get the error message "Missing required parameters recaptcha!".

When I remove the pw forgotten page from the list of forms to apply reCaptcha to nothing happens on submit. The page reloads and no message appears. I also don't receive an email.

Now when I add the pw form the to the "Custom Form Position" section like this:

Form Post Paths: customer/account/forgotpasswordpost/
CSS Selectors: #form-validate

... the reCaptcha shows up once I click the submit button. But it still does not work as the page simply reloads and display this error message: "The request is invalid or malformed.".

This module works fine in other sections like admin login. But I also have this error: https://github.com/mageplaza/magento-2-google-recaptcha/issues/22

**Comment by Arthas7895** [comment]
Outside the front end, our module only supports captcha invisible and captcha v2(http://prntscr.com/opgyhq). Please make sure you are using these 2 things. Currently, we are updating the module to use captcha v3 for the module and will finish it ASAP

**Comment by OvalMedia** [comment]
I am talking about the frontend and I know there is a difference between front- and backend. This module works fine in the frontend on the login page for instance. It fails on the password forgotten page.

**Comment by OvalMedia** [comment]
So basically in the frontend it only works on the login.

**Comment by Arthas7895** [comment]
In this regard, we will need to debug on your site. So for your convenience, please contact us here
https://www.mageplaza.com/contact.html
so I can check and solve your problem

**Comment by enr-beck** [comment]
> Outside the front end, our module only supports captcha invisible and captcha v2(http://prntscr.com/opgyhq). Please make sure you are using these 2 things. Currently, we are updating the module to use captcha v3 for the module and will finish it ASAP

Any news on this or can you estimate when it will be finished?
