### ISSUE TITLE
"The request is invalid or malformed" on contact page

### ISSUE THREAD

**Issue by marcinwasilewski** [mageplaza/magento-2-google-recaptcha#34]
Hi,

I enabled the invisible v2 recaptcha on the contact page and configured it using the generated keys. The recaptcha box displays fine, however the contact form gets invalidated due to "The request is invalid or malformed". 
What could be the issue here?

Magento v. 2.2.7

**Comment by Arthas7895** [comment]
How much recaptcha version of google are you using? The latest version is 1.1.0
You can open the composer.json file(http://prntscr.com/p29j4z) to see the version and upgrade it if necessary

**Comment by marcinwasilewski** [comment]
After updating to the latest 1.1.0 the problem disappeared. Thanks!
