### ISSUE TITLE
Undefined index: id in Iterator.php on line 63

### ISSUE THREAD

**Issue by cralls** [mageplaza/magento-2-google-recaptcha#35]
Does not work with 2.2.6. Stores->Configuration throws error:

Undefined index: id in Iterator.php on line 59

**Comment by Arthas7895** [comment]
Have you installed our core module yet? If not, you can download and install it here
https://github.com/mageplaza/module-core
If already installed, re-install the captcha module again by going into the database, looking in the setup_module table and deleting the Mageplaza_GoogleRecaptcha line. Then run the upgrade and deploy commands again

**Comment by cralls** [comment]
Oh ok, I didn't realize there was a core module required. Ok, that makes
sense, thank you! This resolves the issue.

*Casey Ralls*
<https://plus.google.com/u/0/b/111960571789264200297/111960571789264200297/posts/p/pub>

<https://www.facebook.com/pages/Vector-Network-Solutions-eCommerce-Custom-PHP-Development-Services/51307794206>
           <http://www.youtube.com/user/ax10m>
Web Developer | cralls@vectorns.com | 208.572.0468 | www.vectorns.com

**Comment by Arthas7895** [comment]
Great! Glad to hear your problem has been resolved. I will close this issue here
Have a nice day!
