### ISSUE TITLE
Visible recaptcha in newsletter form

### ISSUE THREAD

**Issue by alex5513** [mageplaza/magento-2-google-recaptcha#36]
Hi,

I want to add visible recpatcha in newsletter form, but it does not work.

![Capture d’écran 2019-09-25 à 17 28 03](https://user-images.githubusercontent.com/6359584/65615971-892f4b80-dfba-11e9-963b-67a2fc525ff0.png)

For no custom forms (login, register etc), visible recaptcha appears correctly.

Thanks for your help.

Alexis

**Comment by Arthas7895** [comment]
First, make sure you have installed the lib for the Google Recaptcha module and your newsletter form is created by Core Magento.
This is the link lib of Google Recaptcha module
https://github.com/mageplaza/magento-2-google-recaptcha/tree/library || http://prntscr.com/pb2382

**Comment by Desmond-Mageplaza** [comment]
As there is no update for this problem, I will close this issue.
If any problem arises in the future, you can always reopen this issue or create a new one.
Thank you for using Mageplaza extension service.
