### ISSUE TITLE
Error: reCAPTCHA placeholder element must be an element or id

### ISSUE THREAD

**Issue by rpelorosso** [mageplaza/magento-2-google-recaptcha#37]
Hi! 

I installed magento2-google-recaptcha (1.1.0) using composer in Magento 2.3.2.  
I'm trying to setup visible recaptcha in the newsletter submission form. I've configured the Key and Secret key, and have the following config set:

![image](https://user-images.githubusercontent.com/6107574/65990758-8d4be500-e462-11e9-80b5-c99cb5948f4a.png)

This is the form:

![image](https://user-images.githubusercontent.com/6107574/65990876-cbe19f80-e462-11e9-9822-9bc51bab41ad.png)

However, When filling the subscription form in the frontend, I'm getting the following error:

`Error: reCAPTCHA placeholder element must be an element or id`

I've been trying to solve it but I haven't been able to. Do you know what might be happening? 

thank you!

**Comment by Arthas7895** [comment]
It looks like the captcha box didn't render properly (normally the system will find the submit button in your form and render the captcha in front of it). Did you use any 3rd extension to change that form? turn it off and use Magento 2. default form if it still can't solve the problem, you can create a ticket here and we will check it directly on your site.
https://www.mageplaza.com/contact.html
Thank you very much!

**Comment by andirosu** [comment]
I second this.  If you try to use it on Magento 2.2.5, on the form.subscribe block defined in `vendor/magento/module-newsletter/view/frontend/layout/default.xml:14`, the `vendor/mageplaza/module-google-recaptcha/view/frontend/web/js/captcha.js` will fail to insert the recaptcha placeholder  because the template used by the block doesn't have the` .actions-toolbar `element.
  ```

                        var buttonElement = element.find('button[type=button]').length > 0 ? element.find('button[type=button]') : element.find('button[type=submit]');
                        var divCaptcha    = $('<div class="g-recaptcha"></div>');
                        var divAction     = $('.actions-toolbar');
                        divCaptcha.attr('id', 'mp' + '_recaptcha_' + number);

                        if (self.options.type === 'visible') {
                            if (element.attr('id') === 'mpageverify-form') {
                                element.find('.mpageverify-verify-action').before(divCaptcha);
                            } else {
                                element.find(divAction).before(divCaptcha);
                            }
                        } else {
                            element.append(divCaptcha);
                        } <-- fails to append, hence the error.
```

**Comment by Arthas7895** [comment]
Exactly, the google Recaptcha module will render the captcha before the submit form button. Normally it relies on div .actions-toolbar. If your current form does not exist, you can search using js to navigate to the submit button in your form

**Comment by Arthas7895** [comment]
It's been 7 days without a response from you, I'll close the problem here
Have a nice day!

**Comment by salman231** [comment]
I'm getting this same issue,Magento version 2.3.4 EE, I have two themes one for my desktop and one for mobile view , Captcha works fine for desktop view and same code is rendering for mobile but captcha not showing in the mobile view. It has the same error in console. Also I have .actions-toolbar class in both mobile and desktop view
