### ISSUE TITLE
Class 'ReCaptcha\ReCaptcha' not found 

### ISSUE THREAD

**Issue by killday** [mageplaza/magento-2-google-recaptcha#38]
Class 'ReCaptcha\ReCaptcha' not found in app/code/Mageplaza/GoogleRecaptcha/Helper/Data.php:316

**Comment by killday** [comment]
Download the lib but can't install it. Which is the correct way to install ?
In the lib/internal/Mageplaza I have folder BrowserDetector and file registration.php which contain Class MageplazaSplClassLoader. Do I have to replace this file ? Try to remove/replace it but then can't setup:upgrade

**Comment by Arthas7895** [comment]
Please download the lib file (https://prnt.sc/peqt0o)and extract it according to the path
lib\internal\Mageplaza\Recaptcha || https://prnt.sc/peqtje

**Comment by killday** [comment]
That is what I did. But the result is the same. Then I try to disable it at least with the command from the readme file - php bin/magento module:disable Mageplaza_Recaptcha - which is wrong it should be php bin/magento module:disable Mageplaza_GoogleRecaptcha and the result is:
Unable to change status of modules because of the following constraints:
Cannot disable Mageplaza_GoogleRecaptcha because modules depend on it:
Mageplaza_Security: Mageplaza_Security->Mageplaza_GoogleRecaptcha

![image](https://user-images.githubusercontent.com/6714294/66198216-d767dd00-e693-11e9-88c1-32193aa06219.png)

**Comment by Arthas7895** [comment]
You can run upgrade and deploy one more time and check the results

**Comment by killday** [comment]
Same results. I'm deleting and starting all over.

**Comment by Arthas7895** [comment]
Ok, you try to install the module from the beginning (Note that the module needs a core version of 1.4.5 or higher). Please make sure you are using the required versions

**Comment by Arthas7895** [comment]
it's been 7 days without a response from you, I'll close the problem here
Have a nice day!
