### ISSUE TITLE
It is not working

### ISSUE THREAD

**Issue by sibi4586** [mageplaza/magento-2-google-recaptcha#4]
I downloaded your Mageplaza_GoogleRecaptcha from github and installed to our magento 2.2.4 site.

Same time I created reCaptcha key from Google (https://www.google.com/recaptcha/) 

I enabled the extension and deployed via SSH.

Then enabled from back-end and added keys which I copied from google reCaptcha key section. Assigned to frontend customer signup page.

But I checked signup page after cleaning and flushing cache nothing happened

Thanks

**Comment by MaxxLuong** [comment]
Close due to no response in 7 days
