### ISSUE TITLE
Recaptcha type not showing for frontend configuration

### ISSUE THREAD

**Issue by asantisan** [mageplaza/magento-2-google-recaptcha#40]
version 1.1.0:
Magento ver. 2.2.5
(documentation example)
![screenshot-docs mageplaza com-2019 11 22-13_50_12](https://user-images.githubusercontent.com/7467510/69444464-2c88ac80-0d2f-11ea-81c9-7d900875204f.png)
(current site)
![screenshot-mcstaging hipot com-2019 11 22-13_52_40](https://user-images.githubusercontent.com/7467510/69444596-6e195780-0d2f-11ea-9e59-1f9fa8ae6e65.png)

![Screenshot from 2019-11-22 13-52-53](https://user-images.githubusercontent.com/7467510/69444627-7ffafa80-0d2f-11ea-8b84-62774a3b9bf9.png)

The option is not showing in the frontend configuration - adminhtml/system.xml has the field added though

**Comment by Desmond-Mageplaza** [comment]
Hi @asantisan 

The Captcha Type options are taken from this file http://prntscr.com/q1k8ji
Am I am certain that the file is present in the Master branch.

Did you update the module properly?
Make sure that Magento 2 cache, browser cache, and server cache are flushed

**Comment by Desmond-Mageplaza** [comment]
This issue is closed due to inactivity for more than 7 days.
Please reopen the issue if the problem still persists.
Thanks
