### ISSUE TITLE
"This site key is not enabled for the invisible captcha" on V2 Invisible Badge

### ISSUE THREAD

**Issue by scottkouri** [mageplaza/magento-2-google-recaptcha#41]
Working with Zoho Forms and I am receiving the This site key is not enabled for the invisible captcha.
error for an V2 invisible bade after I enter the site key and secret key.

Zoho said this is an issue on the Google end. What additional step is needed to fix this?

**Comment by Desmond-Mageplaza** [comment]
Hi @scottkouri 
The message has stated the error pretty straight forward.
Maybe you have mistaken the Invisible Captcha key and visible Captcha key.
Also, Google has just released Captcha V3 recently so make sure you did not mistake its API keys

You should check the API keys again and make sure the keys are matched for the Captcha type

**Comment by Desmond-Mageplaza** [comment]
This issue is closed due to inactivity for more than 7 days.
Please reopen the issue if the problem still persists.
Thanks
