### ISSUE TITLE
Captcha validation is not working

### ISSUE THREAD

**Issue by ravikant19** [mageplaza/magento-2-google-recaptcha#42]
When we enter the useraname and password in login form, this is submitting without validating the login captcha, can you Guys check this and give me an appropriate solution for this bug.

Thanks,
Rand

**Comment by Arthas7895** [comment]
I am very sorry about your problem. You can download the attached file at the link
Where have you installed Google Recaptcha\Observer\Captcha.php
[Captcha (1).zip](https://github.com/mageplaza/magento-2-google-recaptcha/files/3942886/Captcha.1.zip)

**Comment by shibinvr** [comment]
Hi @Arthas7895 , Above patch for backend validation. Is it possible to add frontend validation?

**Comment by Arthas7895** [comment]
@shibinvr The patch I submitted above will fix all forms outside the frontend when submitting the form without selecting the captcha

**Comment by Arthas7895** [comment]
It's been 7 days since I received a response from you, so I'll close this issue here
Thank you very much!
