### ISSUE TITLE
Seems to be completely useless

### ISSUE THREAD

**Issue by OvalMedia** [mageplaza/magento-2-google-recaptcha#43]
It is installed correctly (also with mageplaza support) and it also seems to work as expected.
My store still gets flooded with bot signups. Has reCaptcha been cracked by the spammers?
Does anybody else have this problem?

**Comment by Arthas7895** [comment]
Are you using visible captcha? If yes, you can download and replace the file I edited in this issue || https://github.com/mageplaza/magento-2-google-recaptcha/issues/42

**Comment by Arthas7895** [comment]
It's been 7 days since I haven't heard from you, so I'll close this issue here.
Thank you!
