### ISSUE TITLE
Missing Url in "Form Post Paths" configuration field!

### ISSUE THREAD

**Issue by bharatvimirlab** [mageplaza/magento-2-google-recaptcha#45]
Customer register form showing error **Missing Url in "Form Post Paths" configuration field!** while saving the form in Magento 2.3.4

[http://prntscr.com/rg8bjm](url)

**Comment by Arthas7895** [comment]
It seems that your form has been affected by another 3rd module and changed the processing path. Turn on the browser F12 and navigate to the form action here (https://prnt.sc/ri529j), then fill in the Form Post Paths field(https://prnt.sc/ri52je)(https://prnt.sc/ri52zt). 
Then flush the cache and try again.

**Comment by bharatvimirlab** [comment]
@Arthas7895 thank you for the information. It was some misconfiguration in extension settings. It's solved now. Thanks! 👍

**Comment by Arthas7895** [comment]
OK, I will close this issue here
Have a nice day!
