### ISSUE TITLE
Missing required parameters

### ISSUE THREAD

**Issue by subineseller** [mageplaza/magento-2-google-recaptcha#46]
After installing the Google Recaptcha Module an error is showing in console "Error: Missing required parameters: sitekey" and captcha is not showing in front end login and registration ..

I have installed library file also.still no change.
 
What is the cause of this issue.

How can it be resolved.

Please help to fix this issue ASAP.

**Comment by Arthas7895** [comment]
You need to check the google key configuration here(https://prnt.sc/rs5aot). Maybe you haven't filled it in yet, they won't be able to render captcha
Also, please make sure you are using the correct captcha type you have configured here(https://prnt.sc/rs5bqq)

**Comment by subineseller** [comment]
Hi
I Have configured all the settings.
Now also i have rechecked it. but this is not working.
i try to generate new key and this also does not fix the error.
https://prnt.sc/rs6dby
https://prnt.sc/rs6euz

**Comment by Arthas7895** [comment]
This module only supports recatpcha v2, it does not support recaptcha v3 yet. You need to recreate a new key pair

**Comment by Arthas7895** [comment]
It's been over 7 days without a response from you, so I'll close this issue here
Thanks!
