### ISSUE TITLE
Bypassing the captcha

### ISSUE THREAD

**Issue by sergeyscorra** [mageplaza/magento-2-google-recaptcha#49]
I'm able to bypass the captcha if I delete the validation checkbox element (captcha.js line 111) on the frontend. If it is missing, it is possible to submit the form. In the Observer/Captcha.php, $this->_request->getParam('g-recaptcha-response') is calculated as an empty string, that successfully bypasses comparisons with NULL.

**Comment by Arthas7895** [comment]
In fact, we add captcha checking in js file to fix the forms using ajax to handle, they may not pass captcha into the data sent so your use of $ this ->_ request->getParam ('g-recaptcha-response') is useless. In the new version, I fixed it by taking one more time of data from the ajax processing forms
https://prnt.sc/sal2dy

**Comment by sergeyscorra** [comment]
I see. This may work out if we use ajax submit. But in my case, the form is submitted via a regular post request. Because of that, the condition on the line 131 evaluates as 'true'. $response on line 133 becomes ['message' => 'The response parameter is missing.'], and this error message doesn't go anywhere. We successfully pass the validation.

**Comment by Arthas7895** [comment]
You can change the code (https://prnt.sc/salkw0), clean the cache and your problem will be resolved

**Comment by sergeyscorra** [comment]
Yes, I have changed that condition to if (!empty($captcha)) (in order to include both null and "" cases), and that workes fine for me.
