### ISSUE TITLE
Invisible re captcha badge is not showing in some forms

### ISSUE THREAD

**Issue by darsadask** [mageplaza/magento-2-google-recaptcha#51]
Invisible re captcha badge is not showing in some form in front end 

Site url 
https://phoenixdistributors.com.au/

Steps done for installation
----------------------------------
composer require mageplaza/module-google-recaptcha
php bin/magento setup:upgrade
php bin/magento setup:static-content:deploy

i execute all this command and add the details key & secret key and save the config and then refresh the cachea but the badge is not seen in some forms

https://phoenixdistributors.com.au/contact-us.html **not visible**
https://phoenixdistributors.com.au/contact-us/trade-account.html **Visble**

**Comment by Arthas7895** [comment]
Since you have created a ticket on this issue in our ticket system, I will close this issue here
Thank you very much!
