### ISSUE TITLE
Error: Missing required parameters: sitekey

### ISSUE THREAD

**Issue by MirkoHuf** [mageplaza/magento-2-google-recaptcha#53]
Hi,

i read all the other issues related to "Error: Missing required parameters: sitekey" - but no one solves my problem.

I have created 2 V2 Google Recaptcha Code - one for invisible and one for visible. I also tried booth options - a visible recaptcha for the "create an account" page and also the invisible. Booth shows me the same problem:

Uncaught (in promise) Error: Missing required parameters: sitekey
    at new kP (VM2385 recaptcha__de.js:444)
    at v4.<anonymous> (VM2385 recaptcha__de.js:249)
    at new v4 (VM2385 recaptcha__de.js:497)
    at Array.<anonymous> (VM2385 recaptcha__de.js:343)
    at eval (eval at require.load (7330e36df9a6fdb1efa463ffa26e05b4.min.js:173), <anonymous>:8:28)
    at Array.forEach (<anonymous>)
    at window.recaptchaOnload (eval at require.load (7330e36df9a6fdb1efa463ffa26e05b4.min.js:173), <anonymous>:5:40)

Magento Version is 2.2.8

How can I debug this error or where can I look? Can you help please?

Thanks in advance
Mirko

**Comment by HuyPhuc98** [comment]
Hi,
You need to check the google key configuration here(https://prnt.sc/rs5aot). Maybe you haven't filled it in yet, they won't be able to render captcha
Also, please make sure you are using the correct captcha type you have configured here(https://prnt.sc/rs5bqq)

Thank you!

**Comment by MirkoHuf** [comment]
Hi . 
We've checked that and everything looks fine. 
We have also checked various new systems with V2 (visible and invisible) and also V3 - the same error always appears in any kind of combination.

**Comment by HuyPhuc98** [comment]
Hi,
Please check that you have installed the library or not?
Thank you!

**Comment by MirkoHuf** [comment]
We installed the magento mageplaza recaptcha module - nothing else. 
I could not find any further information in the installation instructions.

Which library must be located where?

**Comment by HuyPhuc98** [comment]
Hi,

I mean, the library of the Google Recaptcha module, is located in the lib\internal\Mageplaza directory.
Did you install it?

Thank you!

**Comment by MirkoHuf** [comment]
mmm I would say - it's not there:
![image](https://user-images.githubusercontent.com/7764831/87123705-92f31880-c287-11ea-82ac-76cb895dcdd4.png)

But I made every step from here: https://docs.mageplaza.com/google-recaptcha/#installation

Something that I miss?

**Comment by MirkoHuf** [comment]
Ohhhh I miss the bottom of the page "Refer the guide to download the library". It's a little bit "hidden" :-)

**Comment by HuyPhuc98** [comment]
Hi,

You can download the Google Recaptcha module lib here:
https://drive.google.com/file/d/1tXvWFc88SgUQ9Q_-SDKINGQZV5GtFjj9/view?usp=sharing

Thank you!

**Comment by MirkoHuf** [comment]
![image](https://user-images.githubusercontent.com/7764831/87130043-92ac4a80-c292-11ea-9c90-a568de3236b2.png)

Steps I made:
composer update
rm -rf var/view_preprocessed/* 
php bin/magento cache:flush 
php bin/magento setup:upgrade 
php bin/magento setup:di:compile
php bin/magento deploy:mode:set production

But the error stil exist.
Again I tried both variants (visible and invisible) - the Google key is definitely the right one (V2 once for visible, once for invisible).

Any more ideas?

**Comment by HuyPhuc98** [comment]
Hi,

You can refer to the following articles for your problem:
https://stackoverflow.com/questions/49174555/invisible-recaptcha-missing-required-parameters-sitekey
https://github.com/sarneeh/reaptcha/issues/18

Thank you!

**Comment by MirkoHuf** [comment]
Hi thank you for the link. But it dosn't help. 
I put the code:
<script src='https://www.google.com/recaptcha/api.js?onload=onloadCallback&render=explicit' async defer></script>
for a test into the header and also in a second test into the footer - I got the same problem as before.

**Comment by HuyPhuc98** [comment]
Hi,

Can you tell me which version of the Google Recaptcha module you are using?
Thank you!

**Comment by MirkoHuf** [comment]
![image](https://user-images.githubusercontent.com/7764831/88151529-1d7e3500-cc03-11ea-80ce-9cf4669d4b10.png)

**Comment by HuyPhuc98** [comment]
Hi,

Please upgrade the Google Recaptcha module to the latest version.
You can download it here: https://github.com/mageplaza/magento-2-google-recaptcha

Thank you!

**Comment by HuyPhuc98** [comment]
We will close this issue due no response within 7 days. If your problem persists, please let us know further detailed report.
