### ISSUE TITLE
Uncaught Error: Class 'ReCaptcha\ReCaptcha' not found 

### ISSUE THREAD

**Issue by Daniel-Bertagnolli** [mageplaza/magento-2-google-recaptcha#58]
I have the module installed and it works on some forms (create new user, for example) but for some reason on the "forgot password" page, when I submit the form I get the error: 

> Uncaught Error: Class 'ReCaptcha\ReCaptcha' not found 

Now, I've tried #28 proposed fix but the link provided it's dead (404), same in the docs the link it's the same any idea how to fix this, or where to download the library file? 

I just find it a bit weird that the recaptcha module works on some forms and not on others, maybe the issue it's another one

**Comment by HuyPhuc98** [comment]
Hi,

Please download the library for the Google Recaptcha module via the following driver link:
https://drive.google.com/file/d/1tXvWFc88SgUQ9Q_-SDKINGQZV5GtFjj9/view?usp=sharing
Thank you!

**Comment by Daniel-Bertagnolli** [comment]
> Hi,
> 
> Please download the library for the Google Recaptcha module via the following driver link:
> https://drive.google.com/file/d/1tXvWFc88SgUQ9Q_-SDKINGQZV5GtFjj9/view?usp=sharing
> Thank you!

Thank you, now it's working!
