### ISSUE TITLE
undefined isEnable()

### ISSUE THREAD

**Issue by Parrotmk** [mageplaza/magento-2-google-recaptcha#6]
Fatal error: Uncaught Error: Call to undefined method Mageplaza\GoogleRecaptcha\Helper\Data::isEnabled() in /home/jasminfi/public_html/app/code/Mageplaza/GoogleRecaptcha/Observer/Captcha.php:101 Stack trace: #0 /home/jasminfi/public_html/vendor/magento/framework/Event/Invoker/InvokerDefault.php(72): Mageplaza\GoogleRecaptcha\Observer\Captcha->execute(Object(Magento\Framework\Event\Observer)) #1 /home/jasminfi/public_html/vendor/magento/framework/Event/Invoker/InvokerDefault.php(60): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod(Object(Mageplaza\GoogleRecaptcha\Observer\Captcha), Object(Magento\Framework\Event\Observer)) #2 /home/jasminfi/public_html/vendor/magento/framework/Event/Manager.php(66): Magento\Framework\Event\Invoker\InvokerDefault->dispatch(Array, Object(Magento\Framework\Event\Observer)) #3 /home/jasminfi/public_html/generated/code/Magento/Framework/Event/Manager/Proxy.php(95): Magento\Framework\Event\Manager->dispatch('controller_acti...', Array) #4 /home/jasminfi/public_html/vendor/mag in /home/jasminfi/public_html/app/code/Mageplaza/GoogleRecaptcha/Observer/Captcha.php on line 101

In have already created google captcha key and enabled the module from backend. please suggest

**Comment by Desmond-MagePlaza** [comment]
Hi, 

Did you install MagePlaza core module?

**Comment by Parrotmk** [comment]
Yes, It is already installed in 
app/code/Mageplaza/Core

**Comment by Desmond-MagePlaza** [comment]
Please make sure the core module is updated to the latest version which is v 1.3.13

**Comment by Kenny1994** [comment]
Hi. If there are no issues left which are related to missing Mageplaza Core module. I'm going to close this issue.
Thank you!
