### ISSUE TITLE
Captcha not working into checkout page

### ISSUE THREAD

**Issue by ankitcostark** [mageplaza/magento-2-google-recaptcha#69]
http://bfwcr.costarktech.com/

please try to make checkout
payeld@costarktech.com
Ankit@1234

----

test card info
4242424242424242
12/22
123

**Comment by ankitcostark** [comment]
test product url: http://bfwcr.costarktech.com/armariodealmacenamiento.html

**Comment by HuyPhuc98** [comment]
Hi,

Currently, the Google Recaptcha module does not support Magento's default checkout page.
Hope you understand.
Thank you!

**Comment by ankitcostark** [comment]
ok

**Comment by HuyPhuc98** [comment]
Since there are no more problems, I will close this issue for now.

**Comment by ankitcostark** [comment]
okay. but is there any reason that it won't worked for checkout.
