### ISSUE TITLE
The response parameter is missing.

### ISSUE THREAD

**Issue by MerikMag** [mageplaza/magento-2-google-recaptcha#7]
We installed the ggogle-recaptcha module via composer on Magento 2.2.4. Since we had already Mageplaza layered menu installed via copying in app/code, we deleted mage_core module, first and reload it via composer

Fronted is working fine, but we can no longer log in to the backend. On the login page we received a "The response parameter is missing." error message.

Maybe Magento captcha is still active.

**Comment by MyoDaisy** [comment]
Please disable Google Recaptcha module and log in to the backend again.
If you still can not login, please disable Magento Captcha module to see what module is causing the error.

**Comment by MyoDaisy** [comment]
Please let me know if everything has worked again.

**Comment by pablobae** [comment]
Same here with Magento 2.2.5.
I can login in after I disabled Google Recaptcha, but when it's enable on backend, the error appears: response parameter is missing .

**Comment by bien119** [comment]
Hi pablobae,

You got the error on admin page or frontend page?
Did you install google recaptcha library? You can find it with the link below.

- https://github.com/mageplaza/magento-2-google-recaptcha/tree/library

Library path: https://i.imgur.com/Kh8q150.png

**Comment by pablobae** [comment]
The extension is installed correctly. In fact, it works fine on frontend, but if a enable it for backend forms (login and forgot password), the error message appears when you try to login.

**Comment by bien119** [comment]
Hi,
Did you create Google Recaptcha app. App for backend is checkbox, not invisible.

- http://prntscr.com/lqyhcn

I suppose that you are mistaken between invisible and visible app.

**Comment by pablobae** [comment]
humm... I've created (and config) invisible app captcha. 

Is it possible enable invisible captcha for frontend and visible (or checkbox) for backend?

**Comment by Ecksters** [comment]
On Magento 2.2.7, installed the extension via composer, admin settings show up just fine, added the API keys, but the reCaptcha don't appear to be being added to the forms, the forms simply give an error that recaptcha is missing whenever they're submitted.

**Comment by alexvais** [comment]
Same issue here.
