### ISSUE TITLE
Missing required parameters recaptcha! 

### ISSUE THREAD

**Issue by pablobae** [mageplaza/magento-2-google-recaptcha#8]
It doesn't work on Magento 2.2.5 forms that are added on cms pages with 

`{{block class="Magento\Contact\Block\ContactForm" name="contactForm" template="Magento_Contact::form.phtml"}}`

When the form is sent, it returns: Missing required parameters

**Comment by MyoDaisy** [comment]
Please add the post path of the form in **Form Post Paths** https://prnt.sc/l9qti4

**Comment by pablobae** [comment]
I added it.. but I didn't add the ID of the form. Thank you.
