### ISSUE TITLE
[Deprecation] 'webkitURL' is deprecated. Please use 'URL' instead.

### ISSUE THREAD

**Issue by trucatchtraps** [mageplaza/magento-2-google-recaptcha#9]
I have been receiving this issue: [Deprecation] 'webkitURL' is deprecated. Please use 'URL' instead. It appears to be an issue with Google Chrome. I have found fixes for the issue by simply doing a google sear of the Deprecation.

**Comment by trucatchtraps** [comment]
Hmm....seems to have been a temporary issue because I am not seeing it anymore.

**Comment by Desmond-MagePlaza** [comment]
Hi, 
I think it was just a residue data from the previous page, you just need to refresh the page several times and the error is gone.

**Comment by Desmond-MagePlaza** [comment]
Hi,
Since this is just a temporary problem, this issue will be closed.
